// Sign-in, account and billing strings, localized. Plain (no node:fs) so both
// server pages and the client forms can import it. The API's own error text is
// English-only, so every error the pages can show has a key here.

import { DEFAULT_LOCALE } from './i18n'

export const ACCOUNT_STRINGS = {
  en: {
    signIn: 'Sign in',
    signOut: 'Sign out',
    back: 'Back',
    working: 'One moment…',

    loginTitle: 'Sign in',
    registerTitle: 'Create account',
    forgotTitle: 'Reset password',
    loginIntro: 'One account for everything on studio.raoul. It’s the same account you use in the apps.',
    email: 'Email',
    emailPlaceholder: 'you@company.com',
    password: 'Password',
    newPassword: 'New password',
    passwordHint: 'at least 8 characters',
    firstName: 'First name',
    lastName: 'Last name',
    code: 'Code',
    codePlaceholder: '6 digits',
    loginButton: 'Sign in',
    registerButton: 'Create account',
    sendCode: 'Send code',
    resetButton: 'Set password',
    toRegister: 'No account yet? Create one',
    toLogin: 'Already have an account? Sign in',
    toForgot: 'Forgot your password?',
    codeSent: 'If there’s an account for that email, we’ve sent it a 6-digit code. The code works for 15 minutes.',
    newCode: 'Send a new code',

    accountTitle: 'Account',
    signedInAs: 'Signed in as',
    yourApps: 'Apps',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'Plans, passes and invoices for your Poofy teams.',
        pricing: 'Pricing',
        billing: 'Billing',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'Plans and passes for Poofy teams. Buy on the web, and your team has it in the app straight away.',
    pricingNote: 'Prices in euros.',
    pricesUnavailable: 'Prices are unavailable right now. Please try again later.',
    monthly: 'Monthly',
    yearly: 'Yearly',
    perMonth: '/ month',
    perYear: '/ year',
    oneOff: 'one-off',
    getStarted: 'Get started',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["Every project in your team unlocked", "Monthly or yearly", "Switch plans or cancel any time; it runs until the end of the paid period"] },
      agency: { name: 'Agency', text: '', features: ["Every project in your team unlocked", "Monthly or yearly", "Switch plans or cancel any time; it runs until the end of the paid period"] },
      event_pass: { name: 'Event Pass', text: "One event, one payment.", features: ["Unlocks one project", "One-time payment, no expiry", "Stays unlocked even if a plan ends"] },
      season_pass: { name: 'Season Pass', text: "A whole season, without a subscription.", features: ["Unlocks every project in your team for 4 months", "One-time payment, no subscription", "Buying another adds 4 months"] },
    },

    billingTitle: 'Billing',
    team: 'Team',
    teams: 'Your teams',
    currentPlan: 'Current plan',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'Active',
      trialing: 'Trial',
      past_due: 'Payment overdue',
      canceled: 'Canceled',
    },
    renewsOn: 'Renews on {date}',
    cancelsOn: 'Cancels on {date}',
    seasonPassUntil: 'Season Pass until {date}',
    manageBilling: 'Manage billing',
    manageHint: 'Change or cancel your plan, update your card, download receipts.',
    choosePlan: 'Choose a plan',
    buy: 'Buy',
    subscribe: 'Subscribe',
    passes: 'Passes',
    project: 'Project',
    noProjects: 'There are no projects without a pass. Create a project in the app first.',
    invoices: 'Invoices',
    noInvoices: 'No invoices yet.',
    invoiceView: 'View',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'Paid',
      open: 'Open',
      void: 'Void',
      uncollectible: 'Unpaid',
      draft: 'Draft',
    },
    membersOnly: 'Only team owners and admins can manage billing.',
    noTeams: 'You’re not in a team yet. Create one here, and it appears in the app too.',
    createTeam: 'Create a team',
    teamName: 'Team name',
    teamPlaceholder: 'My team',
    createButton: 'Create team',

    successTitle: 'Thank you',
    successWaiting: 'Confirming your payment…',
    successDone: 'Payment received. Your team has it now.',
    successSlow: 'Your payment is still being confirmed. This can take a minute. Check your billing page again shortly.',
    toBilling: 'Go to billing',
    cancelTitle: 'Checkout canceled',
    cancelText: 'Nothing was charged. You can choose a plan again at any time.',

    errors: {
      invalid_credentials: 'Wrong email or password.',
      email_taken: 'There’s already an account with that email. Sign in instead.',
      invalid_details: 'Check your details: a valid email, your name, and a password of at least 8 characters.',
      password_short: 'The password needs at least 8 characters.',
      invalid_email: 'Enter a valid email address.',
      wrong_code: 'That code is wrong or has expired.',
      too_many: 'Too many wrong tries. Request a new code.',
      already_subscribed: 'This team already has a subscription. Change it under Manage billing.',
      pass_exists: 'That project already has a pass.',
      nothing_bought: 'This team hasn’t bought anything yet.',
      forbidden: 'Only team owners and admins can do this.',
      not_found: 'That team or project wasn’t found.',
      invalid_team: 'Give the team a name.',
      unavailable: 'This is unavailable right now. Please try again later.',
      generic: 'Something went wrong. Please try again.',
    },
  },

  de: {
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    back: 'Zurück',
    working: 'Einen Moment…',

    loginTitle: 'Anmelden',
    registerTitle: 'Konto erstellen',
    forgotTitle: 'Passwort zurücksetzen',
    loginIntro: 'Ein Konto für alles auf studio.raoul. Es ist dasselbe Konto wie in den Apps.',
    email: 'E-Mail',
    emailPlaceholder: 'sie@unternehmen.com',
    password: 'Passwort',
    newPassword: 'Neues Passwort',
    passwordHint: 'mindestens 8 Zeichen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    code: 'Code',
    codePlaceholder: '6 Ziffern',
    loginButton: 'Anmelden',
    registerButton: 'Konto erstellen',
    sendCode: 'Code senden',
    resetButton: 'Passwort festlegen',
    toRegister: 'Noch kein Konto? Jetzt erstellen',
    toLogin: 'Schon ein Konto? Anmelden',
    toForgot: 'Passwort vergessen?',
    codeSent: 'Falls es ein Konto mit dieser E-Mail gibt, haben wir einen 6-stelligen Code dorthin geschickt. Der Code gilt 15 Minuten.',
    newCode: 'Neuen Code senden',

    accountTitle: 'Konto',
    signedInAs: 'Angemeldet als',
    yourApps: 'Apps',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'Pläne, Pässe und Rechnungen für Ihre Poofy-Teams.',
        pricing: 'Preise',
        billing: 'Abrechnung',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'Pläne und Pässe für Poofy-Teams. Im Web kaufen, und Ihr Team hat es sofort in der App.',
    pricingNote: 'Preise in Euro.',
    pricesUnavailable: 'Die Preise sind gerade nicht verfügbar. Bitte später erneut versuchen.',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
    perMonth: '/ Monat',
    perYear: '/ Jahr',
    oneOff: 'einmalig',
    getStarted: 'Loslegen',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["Alle Projekte Ihres Teams freigeschaltet", "Monatlich oder jährlich", "Plan jederzeit wechseln oder kündigen; er läuft bis zum Ende des bezahlten Zeitraums"] },
      agency: { name: 'Agency', text: '', features: ["Alle Projekte Ihres Teams freigeschaltet", "Monatlich oder jährlich", "Plan jederzeit wechseln oder kündigen; er läuft bis zum Ende des bezahlten Zeitraums"] },
      event_pass: { name: 'Event Pass', text: "Ein Event, eine Zahlung.", features: ["Schaltet ein Projekt frei", "Einmalzahlung, ohne Ablaufdatum", "Bleibt freigeschaltet, auch wenn ein Plan endet"] },
      season_pass: { name: 'Season Pass', text: "Eine ganze Saison, ohne Abo.", features: ["Schaltet alle Projekte Ihres Teams für 4 Monate frei", "Einmalzahlung, kein Abo", "Ein weiterer Kauf verlängert um 4 Monate"] },
    },

    billingTitle: 'Abrechnung',
    team: 'Team',
    teams: 'Ihre Teams',
    currentPlan: 'Aktueller Plan',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'Aktiv',
      trialing: 'Testphase',
      past_due: 'Zahlung überfällig',
      canceled: 'Gekündigt',
    },
    renewsOn: 'Verlängert sich am {date}',
    cancelsOn: 'Endet am {date}',
    seasonPassUntil: 'Season Pass bis {date}',
    manageBilling: 'Abrechnung verwalten',
    manageHint: 'Plan ändern oder kündigen, Karte aktualisieren, Belege herunterladen.',
    choosePlan: 'Plan wählen',
    buy: 'Kaufen',
    subscribe: 'Abonnieren',
    passes: 'Pässe',
    project: 'Projekt',
    noProjects: 'Es gibt keine Projekte ohne Pass. Erstellen Sie zuerst ein Projekt in der App.',
    invoices: 'Rechnungen',
    noInvoices: 'Noch keine Rechnungen.',
    invoiceView: 'Ansehen',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'Bezahlt',
      open: 'Offen',
      void: 'Storniert',
      uncollectible: 'Unbezahlt',
      draft: 'Entwurf',
    },
    membersOnly: 'Nur Team-Inhaber und Admins können die Abrechnung verwalten.',
    noTeams: 'Sie sind noch in keinem Team. Erstellen Sie hier eins, es erscheint auch in der App.',
    createTeam: 'Team erstellen',
    teamName: 'Teamname',
    teamPlaceholder: 'Mein Team',
    createButton: 'Team erstellen',

    successTitle: 'Vielen Dank',
    successWaiting: 'Ihre Zahlung wird bestätigt…',
    successDone: 'Zahlung erhalten. Ihr Team hat es jetzt.',
    successSlow: 'Ihre Zahlung wird noch bestätigt. Das kann eine Minute dauern. Schauen Sie gleich noch einmal auf Ihre Abrechnungsseite.',
    toBilling: 'Zur Abrechnung',
    cancelTitle: 'Bezahlung abgebrochen',
    cancelText: 'Es wurde nichts berechnet. Sie können jederzeit erneut einen Plan wählen.',

    errors: {
      invalid_credentials: 'E-Mail oder Passwort ist falsch.',
      email_taken: 'Mit dieser E-Mail gibt es bereits ein Konto. Bitte melden Sie sich an.',
      invalid_details: 'Bitte prüfen Sie Ihre Angaben: eine gültige E-Mail, Ihren Namen und ein Passwort mit mindestens 8 Zeichen.',
      password_short: 'Das Passwort braucht mindestens 8 Zeichen.',
      invalid_email: 'Bitte eine gültige E-Mail-Adresse eingeben.',
      wrong_code: 'Der Code ist falsch oder abgelaufen.',
      too_many: 'Zu viele Fehlversuche. Fordern Sie einen neuen Code an.',
      already_subscribed: 'Dieses Team hat bereits ein Abo. Ändern Sie es unter „Abrechnung verwalten“.',
      pass_exists: 'Dieses Projekt hat bereits einen Pass.',
      nothing_bought: 'Dieses Team hat noch nichts gekauft.',
      forbidden: 'Das können nur Team-Inhaber und Admins.',
      not_found: 'Team oder Projekt wurde nicht gefunden.',
      invalid_team: 'Geben Sie dem Team einen Namen.',
      unavailable: 'Das ist gerade nicht verfügbar. Bitte später erneut versuchen.',
      generic: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
    },
  },

  nl: {
    signIn: 'Inloggen',
    signOut: 'Uitloggen',
    back: 'Terug',
    working: 'Even geduld…',

    loginTitle: 'Inloggen',
    registerTitle: 'Account maken',
    forgotTitle: 'Wachtwoord herstellen',
    loginIntro: 'Eén account voor alles op studio.raoul. Het is hetzelfde account als in de apps.',
    email: 'E-mail',
    emailPlaceholder: 'jij@bedrijf.com',
    password: 'Wachtwoord',
    newPassword: 'Nieuw wachtwoord',
    passwordHint: 'minstens 8 tekens',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    code: 'Code',
    codePlaceholder: '6 cijfers',
    loginButton: 'Inloggen',
    registerButton: 'Account maken',
    sendCode: 'Code sturen',
    resetButton: 'Wachtwoord instellen',
    toRegister: 'Nog geen account? Maak er een',
    toLogin: 'Al een account? Log in',
    toForgot: 'Wachtwoord vergeten?',
    codeSent: 'Als er een account met dat e-mailadres is, hebben we er een code van 6 cijfers naartoe gestuurd. De code werkt 15 minuten.',
    newCode: 'Nieuwe code sturen',

    accountTitle: 'Account',
    signedInAs: 'Ingelogd als',
    yourApps: 'Apps',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'Abonnementen, passes en facturen voor je Poofy-teams.',
        pricing: 'Prijzen',
        billing: 'Betalingen',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'Abonnementen en passes voor Poofy-teams. Koop op het web, en je team heeft het meteen in de app.',
    pricingNote: 'Prijzen in euro’s.',
    pricesUnavailable: 'De prijzen zijn nu niet beschikbaar. Probeer het later opnieuw.',
    monthly: 'Maandelijks',
    yearly: 'Jaarlijks',
    perMonth: '/ maand',
    perYear: '/ jaar',
    oneOff: 'eenmalig',
    getStarted: 'Aan de slag',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["Alle projecten van je team ontgrendeld", "Maandelijks of jaarlijks", "Wissel of zeg op wanneer je wilt; het loopt door tot het einde van de betaalde periode"] },
      agency: { name: 'Agency', text: '', features: ["Alle projecten van je team ontgrendeld", "Maandelijks of jaarlijks", "Wissel of zeg op wanneer je wilt; het loopt door tot het einde van de betaalde periode"] },
      event_pass: { name: 'Event Pass', text: "Eén event, één betaling.", features: ["Ontgrendelt één project", "Eenmalige betaling, verloopt niet", "Blijft ontgrendeld, ook als een abonnement stopt"] },
      season_pass: { name: 'Season Pass', text: "Een heel seizoen, zonder abonnement.", features: ["Ontgrendelt alle projecten van je team voor 4 maanden", "Eenmalige betaling, geen abonnement", "Nog een kopen verlengt met 4 maanden"] },
    },

    billingTitle: 'Betalingen',
    team: 'Team',
    teams: 'Je teams',
    currentPlan: 'Huidig abonnement',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'Actief',
      trialing: 'Proefperiode',
      past_due: 'Betaling achterstallig',
      canceled: 'Opgezegd',
    },
    renewsOn: 'Verlengt op {date}',
    cancelsOn: 'Stopt op {date}',
    seasonPassUntil: 'Season Pass tot {date}',
    manageBilling: 'Betalingen beheren',
    manageHint: 'Abonnement wijzigen of opzeggen, kaart bijwerken, bonnen downloaden.',
    choosePlan: 'Kies een abonnement',
    buy: 'Kopen',
    subscribe: 'Abonneren',
    passes: 'Passes',
    project: 'Project',
    noProjects: 'Er zijn geen projecten zonder pass. Maak eerst een project in de app.',
    invoices: 'Facturen',
    noInvoices: 'Nog geen facturen.',
    invoiceView: 'Bekijken',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'Betaald',
      open: 'Open',
      void: 'Vervallen',
      uncollectible: 'Onbetaald',
      draft: 'Concept',
    },
    membersOnly: 'Alleen eigenaren en beheerders van een team kunnen betalingen beheren.',
    noTeams: 'Je zit nog niet in een team. Maak er hier een; het verschijnt ook in de app.',
    createTeam: 'Team maken',
    teamName: 'Teamnaam',
    teamPlaceholder: 'Mijn team',
    createButton: 'Team maken',

    successTitle: 'Dank je',
    successWaiting: 'Je betaling wordt bevestigd…',
    successDone: 'Betaling ontvangen. Je team heeft het nu.',
    successSlow: 'Je betaling wordt nog bevestigd. Dat kan een minuutje duren. Kijk zo nog eens op je betalingspagina.',
    toBilling: 'Naar betalingen',
    cancelTitle: 'Betaling afgebroken',
    cancelText: 'Er is niets afgeschreven. Je kunt altijd opnieuw een abonnement kiezen.',

    errors: {
      invalid_credentials: 'E-mail of wachtwoord klopt niet.',
      email_taken: 'Er is al een account met dat e-mailadres. Log in.',
      invalid_details: 'Controleer je gegevens: een geldig e-mailadres, je naam en een wachtwoord van minstens 8 tekens.',
      password_short: 'Het wachtwoord moet minstens 8 tekens hebben.',
      invalid_email: 'Vul een geldig e-mailadres in.',
      wrong_code: 'Die code klopt niet of is verlopen.',
      too_many: 'Te vaak een verkeerde code. Vraag een nieuwe code aan.',
      already_subscribed: 'Dit team heeft al een abonnement. Wijzig het via Betalingen beheren.',
      pass_exists: 'Dat project heeft al een pass.',
      nothing_bought: 'Dit team heeft nog niets gekocht.',
      forbidden: 'Alleen eigenaren en beheerders van het team kunnen dit.',
      not_found: 'Dat team of project is niet gevonden.',
      invalid_team: 'Geef het team een naam.',
      unavailable: 'Dit is nu niet beschikbaar. Probeer het later opnieuw.',
      generic: 'Er ging iets mis. Probeer het opnieuw.',
    },
  },

  es: {
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    back: 'Volver',
    working: 'Un momento…',

    loginTitle: 'Iniciar sesión',
    registerTitle: 'Crear cuenta',
    forgotTitle: 'Restablecer contraseña',
    loginIntro: 'Una cuenta para todo en studio.raoul. Es la misma cuenta que usas en las apps.',
    email: 'Correo',
    emailPlaceholder: 'tu@empresa.com',
    password: 'Contraseña',
    newPassword: 'Nueva contraseña',
    passwordHint: 'al menos 8 caracteres',
    firstName: 'Nombre',
    lastName: 'Apellido',
    code: 'Código',
    codePlaceholder: '6 dígitos',
    loginButton: 'Iniciar sesión',
    registerButton: 'Crear cuenta',
    sendCode: 'Enviar código',
    resetButton: 'Guardar contraseña',
    toRegister: '¿Aún no tienes cuenta? Crea una',
    toLogin: '¿Ya tienes cuenta? Inicia sesión',
    toForgot: '¿Has olvidado tu contraseña?',
    codeSent: 'Si hay una cuenta con ese correo, le hemos enviado un código de 6 dígitos. El código vale 15 minutos.',
    newCode: 'Enviar un código nuevo',

    accountTitle: 'Cuenta',
    signedInAs: 'Sesión iniciada como',
    yourApps: 'Apps',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'Planes, pases y facturas de tus equipos de Poofy.',
        pricing: 'Precios',
        billing: 'Facturación',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'Planes y pases para equipos de Poofy. Compra en la web y tu equipo lo tiene al instante en la app.',
    pricingNote: 'Precios en euros.',
    pricesUnavailable: 'Los precios no están disponibles ahora. Inténtalo más tarde.',
    monthly: 'Mensual',
    yearly: 'Anual',
    perMonth: '/ mes',
    perYear: '/ año',
    oneOff: 'pago único',
    getStarted: 'Empezar',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["Todos los proyectos de tu equipo desbloqueados", "Mensual o anual", "Cambia de plan o cancela cuando quieras; sigue activo hasta el final del periodo pagado"] },
      agency: { name: 'Agency', text: '', features: ["Todos los proyectos de tu equipo desbloqueados", "Mensual o anual", "Cambia de plan o cancela cuando quieras; sigue activo hasta el final del periodo pagado"] },
      event_pass: { name: 'Event Pass', text: "Un evento, un pago.", features: ["Desbloquea un proyecto", "Pago único, sin caducidad", "Sigue desbloqueado aunque termine un plan"] },
      season_pass: { name: 'Season Pass', text: "Una temporada entera, sin suscripción.", features: ["Desbloquea todos los proyectos de tu equipo durante 4 meses", "Pago único, sin suscripción", "Comprar otro añade 4 meses"] },
    },

    billingTitle: 'Facturación',
    team: 'Equipo',
    teams: 'Tus equipos',
    currentPlan: 'Plan actual',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'Activo',
      trialing: 'Prueba',
      past_due: 'Pago pendiente',
      canceled: 'Cancelado',
    },
    renewsOn: 'Se renueva el {date}',
    cancelsOn: 'Termina el {date}',
    seasonPassUntil: 'Season Pass hasta el {date}',
    manageBilling: 'Gestionar facturación',
    manageHint: 'Cambia o cancela tu plan, actualiza tu tarjeta, descarga recibos.',
    choosePlan: 'Elige un plan',
    buy: 'Comprar',
    subscribe: 'Suscribirse',
    passes: 'Pases',
    project: 'Proyecto',
    noProjects: 'No hay proyectos sin pase. Crea primero un proyecto en la app.',
    invoices: 'Facturas',
    noInvoices: 'Aún no hay facturas.',
    invoiceView: 'Ver',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'Pagada',
      open: 'Abierta',
      void: 'Anulada',
      uncollectible: 'Impagada',
      draft: 'Borrador',
    },
    membersOnly: 'Solo los propietarios y administradores del equipo pueden gestionar la facturación.',
    noTeams: 'Aún no estás en ningún equipo. Crea uno aquí; también aparecerá en la app.',
    createTeam: 'Crear un equipo',
    teamName: 'Nombre del equipo',
    teamPlaceholder: 'Mi equipo',
    createButton: 'Crear equipo',

    successTitle: 'Gracias',
    successWaiting: 'Confirmando tu pago…',
    successDone: 'Pago recibido. Tu equipo ya lo tiene.',
    successSlow: 'Tu pago aún se está confirmando. Puede tardar un minuto. Vuelve a mirar tu página de facturación en un momento.',
    toBilling: 'Ir a facturación',
    cancelTitle: 'Pago cancelado',
    cancelText: 'No se ha cobrado nada. Puedes volver a elegir un plan cuando quieras.',

    errors: {
      invalid_credentials: 'Correo o contraseña incorrectos.',
      email_taken: 'Ya existe una cuenta con ese correo. Inicia sesión.',
      invalid_details: 'Revisa tus datos: un correo válido, tu nombre y una contraseña de al menos 8 caracteres.',
      password_short: 'La contraseña necesita al menos 8 caracteres.',
      invalid_email: 'Introduce un correo válido.',
      wrong_code: 'El código es incorrecto o ha caducado.',
      too_many: 'Demasiados intentos fallidos. Pide un código nuevo.',
      already_subscribed: 'Este equipo ya tiene una suscripción. Cámbiala en Gestionar facturación.',
      pass_exists: 'Ese proyecto ya tiene un pase.',
      nothing_bought: 'Este equipo aún no ha comprado nada.',
      forbidden: 'Solo los propietarios y administradores del equipo pueden hacer esto.',
      not_found: 'No se ha encontrado ese equipo o proyecto.',
      invalid_team: 'Ponle un nombre al equipo.',
      unavailable: 'Esto no está disponible ahora. Inténtalo más tarde.',
      generic: 'Algo ha salido mal. Inténtalo de nuevo.',
    },
  },

  fr: {
    signIn: 'Se connecter',
    signOut: 'Se déconnecter',
    back: 'Retour',
    working: 'Un instant…',

    loginTitle: 'Connexion',
    registerTitle: 'Créer un compte',
    forgotTitle: 'Réinitialiser le mot de passe',
    loginIntro: 'Un seul compte pour tout studio.raoul. C’est le même compte que dans les apps.',
    email: 'E-mail',
    emailPlaceholder: 'vous@entreprise.com',
    password: 'Mot de passe',
    newPassword: 'Nouveau mot de passe',
    passwordHint: 'au moins 8 caractères',
    firstName: 'Prénom',
    lastName: 'Nom',
    code: 'Code',
    codePlaceholder: '6 chiffres',
    loginButton: 'Se connecter',
    registerButton: 'Créer un compte',
    sendCode: 'Envoyer le code',
    resetButton: 'Enregistrer',
    toRegister: 'Pas encore de compte ? Créez-en un',
    toLogin: 'Déjà un compte ? Connectez-vous',
    toForgot: 'Mot de passe oublié ?',
    codeSent: 'S’il existe un compte avec cet e-mail, nous lui avons envoyé un code à 6 chiffres. Le code est valable 15 minutes.',
    newCode: 'Envoyer un nouveau code',

    accountTitle: 'Compte',
    signedInAs: 'Connecté en tant que',
    yourApps: 'Apps',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'Formules, pass et factures de vos équipes Poofy.',
        pricing: 'Tarifs',
        billing: 'Facturation',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'Formules et pass pour les équipes Poofy. Achetez sur le web, et votre équipe en profite aussitôt dans l’app.',
    pricingNote: 'Prix en euros.',
    pricesUnavailable: 'Les prix ne sont pas disponibles pour le moment. Réessayez plus tard.',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    perMonth: '/ mois',
    perYear: '/ an',
    oneOff: 'paiement unique',
    getStarted: 'Commencer',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["Tous les projets de votre équipe débloqués", "Mensuel ou annuel", "Changez de formule ou résiliez à tout moment ; elle court jusqu’à la fin de la période payée"] },
      agency: { name: 'Agency', text: '', features: ["Tous les projets de votre équipe débloqués", "Mensuel ou annuel", "Changez de formule ou résiliez à tout moment ; elle court jusqu’à la fin de la période payée"] },
      event_pass: { name: 'Event Pass', text: "Un événement, un paiement.", features: ["Débloque un projet", "Paiement unique, sans expiration", "Reste débloqué même si une formule prend fin"] },
      season_pass: { name: 'Season Pass', text: "Toute une saison, sans abonnement.", features: ["Débloque tous les projets de votre équipe pendant 4 mois", "Paiement unique, sans abonnement", "En racheter un ajoute 4 mois"] },
    },

    billingTitle: 'Facturation',
    team: 'Équipe',
    teams: 'Vos équipes',
    currentPlan: 'Formule actuelle',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'Active',
      trialing: 'Essai',
      past_due: 'Paiement en retard',
      canceled: 'Résiliée',
    },
    renewsOn: 'Renouvellement le {date}',
    cancelsOn: 'Prend fin le {date}',
    seasonPassUntil: 'Season Pass jusqu’au {date}',
    manageBilling: 'Gérer la facturation',
    manageHint: 'Changer ou résilier votre formule, mettre à jour votre carte, télécharger vos reçus.',
    choosePlan: 'Choisir une formule',
    buy: 'Acheter',
    subscribe: 'S’abonner',
    passes: 'Pass',
    project: 'Projet',
    noProjects: 'Aucun projet sans pass. Créez d’abord un projet dans l’app.',
    invoices: 'Factures',
    noInvoices: 'Pas encore de factures.',
    invoiceView: 'Voir',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'Payée',
      open: 'Ouverte',
      void: 'Annulée',
      uncollectible: 'Impayée',
      draft: 'Brouillon',
    },
    membersOnly: 'Seuls les propriétaires et administrateurs de l’équipe peuvent gérer la facturation.',
    noTeams: 'Vous n’êtes encore dans aucune équipe. Créez-en une ici ; elle apparaîtra aussi dans l’app.',
    createTeam: 'Créer une équipe',
    teamName: 'Nom de l’équipe',
    teamPlaceholder: 'Mon équipe',
    createButton: 'Créer l’équipe',

    successTitle: 'Merci',
    successWaiting: 'Confirmation de votre paiement…',
    successDone: 'Paiement reçu. Votre équipe en profite maintenant.',
    successSlow: 'Votre paiement est encore en cours de confirmation. Cela peut prendre une minute. Revenez sur votre page de facturation dans un instant.',
    toBilling: 'Aller à la facturation',
    cancelTitle: 'Paiement annulé',
    cancelText: 'Rien n’a été débité. Vous pouvez choisir une formule à tout moment.',

    errors: {
      invalid_credentials: 'E-mail ou mot de passe incorrect.',
      email_taken: 'Un compte existe déjà avec cet e-mail. Connectez-vous.',
      invalid_details: 'Vérifiez vos informations : un e-mail valide, votre nom et un mot de passe d’au moins 8 caractères.',
      password_short: 'Le mot de passe doit comporter au moins 8 caractères.',
      invalid_email: 'Saisissez une adresse e-mail valide.',
      wrong_code: 'Ce code est incorrect ou a expiré.',
      too_many: 'Trop d’essais incorrects. Demandez un nouveau code.',
      already_subscribed: 'Cette équipe a déjà un abonnement. Modifiez-le via Gérer la facturation.',
      pass_exists: 'Ce projet a déjà un pass.',
      nothing_bought: 'Cette équipe n’a encore rien acheté.',
      forbidden: 'Seuls les propriétaires et administrateurs de l’équipe peuvent faire cela.',
      not_found: 'Équipe ou projet introuvable.',
      invalid_team: 'Donnez un nom à l’équipe.',
      unavailable: 'Ce service n’est pas disponible pour le moment. Réessayez plus tard.',
      generic: 'Une erreur s’est produite. Veuillez réessayer.',
    },
  },

  ar: {
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    back: 'رجوع',
    working: 'لحظة…',

    loginTitle: 'تسجيل الدخول',
    registerTitle: 'إنشاء حساب',
    forgotTitle: 'إعادة تعيين كلمة المرور',
    loginIntro: 'حساب واحد لكل شيء على studio.raoul، وهو الحساب نفسه الذي تستخدمه في التطبيقات.',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'you@company.com',
    password: 'كلمة المرور',
    newPassword: 'كلمة المرور الجديدة',
    passwordHint: '8 أحرف على الأقل',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    code: 'الرمز',
    codePlaceholder: '6 أرقام',
    loginButton: 'تسجيل الدخول',
    registerButton: 'إنشاء حساب',
    sendCode: 'إرسال الرمز',
    resetButton: 'حفظ كلمة المرور',
    toRegister: 'ليس لديك حساب؟ أنشئ حسابًا',
    toLogin: 'لديك حساب؟ سجّل الدخول',
    toForgot: 'نسيت كلمة المرور؟',
    codeSent: 'إذا كان هناك حساب بهذا البريد الإلكتروني، فقد أرسلنا إليه رمزًا من 6 أرقام. الرمز صالح لمدة 15 دقيقة.',
    newCode: 'إرسال رمز جديد',

    accountTitle: 'الحساب',
    signedInAs: 'مسجّل الدخول باسم',
    yourApps: 'التطبيقات',
    apps: {
      'poofy-events': {
        name: 'Poofy Events',
        text: 'الخطط والتذاكر والفواتير لفرقك في Poofy.',
        pricing: 'الأسعار',
        billing: 'الفوترة',
      },
    },

    pricingTitle: 'Poofy Events',
    pricingIntro: 'خطط وتذاكر لفرق Poofy. اشترِ عبر الويب، ويحصل فريقك عليها فورًا في التطبيق.',
    pricingNote: 'الأسعار باليورو.',
    pricesUnavailable: 'الأسعار غير متاحة حاليًا. يُرجى المحاولة لاحقًا.',
    monthly: 'شهري',
    yearly: 'سنوي',
    perMonth: '/ شهريًا',
    perYear: '/ سنويًا',
    oneOff: 'دفعة واحدة',
    getStarted: 'ابدأ الآن',
    // Only facts the API enforces. What sets Pro apart from Agency is still
    // Raoul's call, so neither has a tagline yet.
    plans: {
      pro: { name: 'Pro', text: '', features: ["فتح جميع مشاريع فريقك", "شهريًا أو سنويًا", "غيّر خطتك أو ألغِها في أي وقت، وتستمر حتى نهاية الفترة المدفوعة"] },
      agency: { name: 'Agency', text: '', features: ["فتح جميع مشاريع فريقك", "شهريًا أو سنويًا", "غيّر خطتك أو ألغِها في أي وقت، وتستمر حتى نهاية الفترة المدفوعة"] },
      event_pass: { name: 'Event Pass', text: "فعالية واحدة، دفعة واحدة.", features: ["يفتح مشروعًا واحدًا", "دفعة واحدة، بلا تاريخ انتهاء", "يبقى مفتوحًا حتى لو انتهت الخطة"] },
      season_pass: { name: 'Season Pass', text: "موسم كامل، دون اشتراك.", features: ["يفتح جميع مشاريع فريقك لمدة 4 أشهر", "دفعة واحدة، دون اشتراك", "شراء تذكرة أخرى يضيف 4 أشهر"] },
    },

    billingTitle: 'الفوترة',
    team: 'الفريق',
    teams: 'فرقك',
    currentPlan: 'الخطة الحالية',
    planNames: { free: 'Free', pro: 'Pro', agency: 'Agency' },
    planStatus: {
      active: 'نشطة',
      trialing: 'فترة تجريبية',
      past_due: 'دفعة متأخرة',
      canceled: 'ملغاة',
    },
    renewsOn: 'تتجدّد في {date}',
    cancelsOn: 'تنتهي في {date}',
    seasonPassUntil: 'Season Pass حتى {date}',
    manageBilling: 'إدارة الفوترة',
    manageHint: 'غيّر خطتك أو ألغِها، وحدّث بطاقتك، ونزّل الإيصالات.',
    choosePlan: 'اختر خطة',
    buy: 'شراء',
    subscribe: 'اشترك',
    passes: 'التذاكر',
    project: 'المشروع',
    noProjects: 'لا توجد مشاريع بلا تذكرة. أنشئ مشروعًا في التطبيق أولًا.',
    invoices: 'الفواتير',
    noInvoices: 'لا توجد فواتير بعد.',
    invoiceView: 'عرض',
    invoicePdf: 'PDF',
    invoiceStatus: {
      paid: 'مدفوعة',
      open: 'مفتوحة',
      void: 'ملغاة',
      uncollectible: 'غير مدفوعة',
      draft: 'مسودة',
    },
    membersOnly: 'يمكن لمالكي الفريق ومسؤوليه فقط إدارة الفوترة.',
    noTeams: 'لست في أي فريق بعد. أنشئ فريقًا هنا، وسيظهر في التطبيق أيضًا.',
    createTeam: 'إنشاء فريق',
    teamName: 'اسم الفريق',
    teamPlaceholder: 'فريقي',
    createButton: 'إنشاء الفريق',

    successTitle: 'شكرًا لك',
    successWaiting: 'جارٍ تأكيد الدفع…',
    successDone: 'تم استلام الدفع. أصبح لدى فريقك الآن ما اشتريته.',
    successSlow: 'لا يزال الدفع قيد التأكيد، وقد يستغرق ذلك دقيقة. راجع صفحة الفوترة بعد قليل.',
    toBilling: 'الانتقال إلى الفوترة',
    cancelTitle: 'أُلغي الدفع',
    cancelText: 'لم يُخصم أي مبلغ. يمكنك اختيار خطة في أي وقت.',

    errors: {
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      email_taken: 'يوجد حساب بهذا البريد الإلكتروني بالفعل. سجّل الدخول بدلًا من ذلك.',
      invalid_details: 'تحقّق من بياناتك: بريد إلكتروني صالح، واسمك، وكلمة مرور من 8 أحرف على الأقل.',
      password_short: 'يجب أن تتكوّن كلمة المرور من 8 أحرف على الأقل.',
      invalid_email: 'أدخل بريدًا إلكترونيًا صالحًا.',
      wrong_code: 'الرمز غير صحيح أو منتهي الصلاحية.',
      too_many: 'محاولات خاطئة كثيرة. اطلب رمزًا جديدًا.',
      already_subscribed: 'لدى هذا الفريق اشتراك بالفعل. غيّره من «إدارة الفوترة».',
      pass_exists: 'لدى هذا المشروع تذكرة بالفعل.',
      nothing_bought: 'لم يشترِ هذا الفريق أي شيء بعد.',
      forbidden: 'يمكن لمالكي الفريق ومسؤوليه فقط القيام بذلك.',
      not_found: 'لم يُعثر على الفريق أو المشروع.',
      invalid_team: 'أدخل اسمًا للفريق.',
      unavailable: 'هذه الخدمة غير متاحة حاليًا. يُرجى المحاولة لاحقًا.',
      generic: 'حدث خطأ ما. يُرجى المحاولة مرة أخرى.',
    },
  },
}

export function getAccountStrings(lang) {
  return ACCOUNT_STRINGS[lang] || ACCOUNT_STRINGS[DEFAULT_LOCALE]
}

// '{date}' placeholders.
export function fill(template, values) {
  return template.replace(/\{(\w+)\}/g, (_, k) => values[k] ?? '')
}

// 1900 → '€19', 19000 → '€190' (no cents when whole), in the page's locale.
export function formatMoney(cents, currency, lang) {
  const whole = cents % 100 === 0
  return new Intl.NumberFormat(lang, {
    style: 'currency',
    currency: (currency || 'eur').toUpperCase(),
    minimumFractionDigits: whole ? 0 : 2,
    maximumFractionDigits: whole ? 0 : 2,
  }).format(cents / 100)
}

export function formatDate(value, lang) {
  if (!value) return ''
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return String(value)
  return new Intl.DateTimeFormat(lang, { day: 'numeric', month: 'long', year: 'numeric' }).format(d)
}
