// Newsletter signup + unsubscribe strings, localized. Plain (no node:fs) so it
// can be imported by both server pages and the client signup component.

import { DEFAULT_LOCALE } from './i18n'

export const NEWSLETTER_STRINGS = {
  en: {
    heading: 'The weekly brief',
    sub: 'One email a week — the latest in AI, software and digital products, and what it means for your business.',
    placeholder: 'you@company.com',
    button: 'Subscribe',
    sending: 'Subscribing…',
    success: 'You’re in. Watch your inbox.',
    error: 'Something went wrong. Please try again.',
    invalid: 'Enter a valid email address.',
    consent: 'No spam. Unsubscribe anytime.',
    unsubTitle: 'Unsubscribed',
    unsubOk: 'You’ve been unsubscribed and won’t receive any more newsletters.',
    unsubFail: 'We couldn’t find that subscription — it may already have been removed.',
    backHome: 'Back to raoul.studio',
  },
  de: {
    heading: 'Der wöchentliche Überblick',
    sub: 'Eine E-Mail pro Woche — das Neueste zu KI, Software und digitalen Produkten und was es für Ihr Unternehmen bedeutet.',
    placeholder: 'sie@unternehmen.com',
    button: 'Abonnieren',
    sending: 'Wird abonniert…',
    success: 'Sie sind dabei. Schauen Sie in Ihr Postfach.',
    error: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
    invalid: 'Bitte eine gültige E-Mail-Adresse eingeben.',
    consent: 'Kein Spam. Jederzeit abbestellbar.',
    unsubTitle: 'Abgemeldet',
    unsubOk: 'Sie wurden abgemeldet und erhalten keine Newsletter mehr.',
    unsubFail: 'Wir konnten dieses Abonnement nicht finden — es wurde möglicherweise bereits entfernt.',
    backHome: 'Zurück zu raoul.studio',
  },
  nl: {
    heading: 'De wekelijkse update',
    sub: 'Eén e-mail per week — het laatste over AI, software en digitale producten, en wat het betekent voor je bedrijf.',
    placeholder: 'jij@bedrijf.com',
    button: 'Aanmelden',
    sending: 'Bezig met aanmelden…',
    success: 'Je bent erbij. Hou je inbox in de gaten.',
    error: 'Er ging iets mis. Probeer het opnieuw.',
    invalid: 'Vul een geldig e-mailadres in.',
    consent: 'Geen spam. Altijd uit te schrijven.',
    unsubTitle: 'Uitgeschreven',
    unsubOk: 'Je bent uitgeschreven en ontvangt geen nieuwsbrieven meer.',
    unsubFail: 'We konden dat abonnement niet vinden — het is mogelijk al verwijderd.',
    backHome: 'Terug naar raoul.studio',
  },
  es: {
    heading: 'El resumen semanal',
    sub: 'Un email por semana: lo último en IA, software y productos digitales, y lo que significa para tu negocio.',
    placeholder: 'tu@empresa.com',
    button: 'Suscribirme',
    sending: 'Suscribiendo…',
    success: 'Ya estás dentro. Revisa tu bandeja de entrada.',
    error: 'Algo salió mal. Inténtalo de nuevo.',
    invalid: 'Introduce un correo válido.',
    consent: 'Sin spam. Cancela cuando quieras.',
    unsubTitle: 'Suscripción cancelada',
    unsubOk: 'Te has dado de baja y no recibirás más newsletters.',
    unsubFail: 'No encontramos esa suscripción — puede que ya se haya eliminado.',
    backHome: 'Volver a raoul.studio',
  },
  fr: {
    heading: 'Le point hebdo',
    sub: 'Un email par semaine — l’actualité de l’IA, du software et des produits digitaux, et ce que cela change pour votre entreprise.',
    placeholder: 'vous@entreprise.com',
    button: 'S’abonner',
    sending: 'Inscription…',
    success: 'C’est fait. Surveillez votre boîte mail.',
    error: 'Une erreur est survenue. Réessayez.',
    invalid: 'Saisissez une adresse email valide.',
    consent: 'Pas de spam. Désabonnement à tout moment.',
    unsubTitle: 'Désabonné',
    unsubOk: 'Vous êtes désabonné et ne recevrez plus de newsletters.',
    unsubFail: 'Nous n’avons pas trouvé cet abonnement — il a peut-être déjà été supprimé.',
    backHome: 'Retour à raoul.studio',
  },
  ar: {
    heading: 'الموجز الأسبوعي',
    sub: 'رسالة واحدة كل أسبوع — أحدث ما في الذكاء الاصطناعي والبرمجيات والمنتجات الرقمية، وما يعنيه ذلك لعملك.',
    placeholder: 'you@company.com',
    button: 'اشترك',
    sending: 'جارٍ الاشتراك…',
    success: 'تم اشتراكك. تابع بريدك الوارد.',
    error: 'حدث خطأ ما. حاول مرة أخرى.',
    invalid: 'أدخل بريدًا إلكترونيًا صالحًا.',
    consent: 'بلا إزعاج. يمكنك إلغاء الاشتراك في أي وقت.',
    unsubTitle: 'تم إلغاء الاشتراك',
    unsubOk: 'تم إلغاء اشتراكك ولن تصلك أي نشرات بعد الآن.',
    unsubFail: 'لم نعثر على هذا الاشتراك — ربما أُزيل بالفعل.',
    backHome: 'العودة إلى raoul.studio',
  },
}

export function getNewsletterStrings(lang) {
  return NEWSLETTER_STRINGS[lang] || NEWSLETTER_STRINGS[DEFAULT_LOCALE]
}
