/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    menu: Menu;
    posterRail: PosterRail;
    footer: Footer;
    home: Home;
    contact: Contact;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    posterRail: PosterRailSelect<false> | PosterRailSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * URL slug. e.g. "booking" → /projects/booking
   */
  slug: string;
  /**
   * Display order (1, 2, 3, …) — also rendered as "Project № 0X".
   */
  number: number;
  /**
   * e.g. 2024
   */
  year: string;
  /**
   * Plain-text title used for tabs, rail, prev/next links.
   */
  titlePlain: string;
  /**
   * First line of the big stacked title.
   */
  titleLine1: string;
  /**
   * Optional second line.
   */
  titleLine2?: string | null;
  /**
   * Optional CSS color applied to the second line (e.g. #E92316). Leave blank to inherit the section text color.
   */
  titleLine2Color?: string | null;
  /**
   * Used on the home-page teaser.
   */
  shortDescription: string;
  /**
   * Lead paragraph at the top of the project detail page.
   */
  lead: string;
  /**
   * e.g. "Web · Payments · Calendar · Stripe" — bottom of teaser.
   */
  tagsLine: string;
  /**
   * Compact tag used in the home Selected Work list, e.g. "web, payments".
   */
  shortTag: string;
  colors: {
    bg: string;
    fg: string;
    /**
     * Override color for the giant background numeral. Leave blank to use fg.
     */
    numeralColor?: string | null;
    numeralOpacity: number;
  };
  /**
   * Role / Stack / Status grid on the project detail page.
   */
  info?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Body paragraphs on the project detail page.
   */
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * URL slug, e.g. "about" → /about
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  eyebrow: string;
  titleLine1: string;
  /**
   * Trailing accent character (red dot, etc.)
   */
  titleAccent?: string | null;
  /**
   * Optional opening paragraph displayed below the title.
   */
  lead?: string | null;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  servicesLabel?: string | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  systemsParagraph?: string | null;
  /**
   * Numbered process steps. Numbers are generated automatically (01, 02, …).
   */
  steps?:
    | {
        title: string;
        lead: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  howWeWork?: {
    label?: string | null;
    lead?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    closing?: string | null;
  };
  manifestoLead?: string | null;
  manifestoTail?: string | null;
  /**
   * Override for the vertical rail middle text on this page.
   */
  posterRailMiddle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  number?: T;
  year?: T;
  titlePlain?: T;
  titleLine1?: T;
  titleLine2?: T;
  titleLine2Color?: T;
  shortDescription?: T;
  lead?: T;
  tagsLine?: T;
  shortTag?: T;
  colors?:
    | T
    | {
        bg?: T;
        fg?: T;
        numeralColor?: T;
        numeralOpacity?: T;
      };
  info?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  eyebrow?: T;
  titleLine1?: T;
  titleAccent?: T;
  lead?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  servicesLabel?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  systemsParagraph?: T;
  steps?:
    | T
    | {
        title?: T;
        lead?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  howWeWork?:
    | T
    | {
        label?: T;
        lead?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
        closing?: T;
      };
  manifestoLead?: T;
  manifestoTail?: T;
  posterRailMiddle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  wordmark: string;
  wordmarkHref: string;
  ctaLabel: string;
  ctaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  eyebrow: string;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerLeft?: string | null;
  footerRightLabel?: string | null;
  footerRightHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posterRail".
 */
export interface PosterRail {
  id: string;
  topText: string;
  middleText: string;
  bottomText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  leftText: string;
  rightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hero: {
    prefix: string;
    accent: string;
    suffix: string;
  };
  intro: string;
  selectedWorkLabel: string;
  contact: {
    eyebrow: string;
    beforeLink: string;
    linkLabel: string;
    linkHref: string;
    /**
     * Use a literal "\n" in this field to insert a desktop-only line break (rendered as <br class="hidden md:block">).
     */
    afterLink: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  eyebrow: string;
  titleLine1: string;
  titleLine2: string;
  /**
   * Trailing accent character (red dot, etc.)
   */
  titleAccent?: string | null;
  lead: string;
  form: {
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    companyLabel?: string | null;
    companyOptional?: string | null;
    companyPlaceholder?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    sendLabel?: string | null;
    /**
     * Email address that the mailto: form sends to.
     */
    recipient: string;
  };
  directContact?: {
    label?: string | null;
    email?: string | null;
  };
  /**
   * Override for the vertical rail middle text on this page.
   */
  posterRailMiddle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  wordmark?: T;
  wordmarkHref?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  eyebrow?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerLeft?: T;
  footerRightLabel?: T;
  footerRightHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posterRail_select".
 */
export interface PosterRailSelect<T extends boolean = true> {
  topText?: T;
  middleText?: T;
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  leftText?: T;
  rightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        prefix?: T;
        accent?: T;
        suffix?: T;
      };
  intro?: T;
  selectedWorkLabel?: T;
  contact?:
    | T
    | {
        eyebrow?: T;
        beforeLink?: T;
        linkLabel?: T;
        linkHref?: T;
        afterLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  eyebrow?: T;
  titleLine1?: T;
  titleLine2?: T;
  titleAccent?: T;
  lead?: T;
  form?:
    | T
    | {
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        companyLabel?: T;
        companyOptional?: T;
        companyPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        sendLabel?: T;
        recipient?: T;
      };
  directContact?:
    | T
    | {
        label?: T;
        email?: T;
      };
  posterRailMiddle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}